# Generated by Django 5.1.5 on 2025-01-24 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the post', max_length=255, null=True, verbose_name='image'),
        ),
    ]
