# Generated by Django 5.1.5 on 2025-01-24 21:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='nobody_nrbk5n', help_text='Upload a profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
